version: '3'
services:
  app:
    build: .
    environment:
      - TZ=Asia/Tokyo
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=ap-northeast-1
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/src/bin/app
    working_dir: /src/bin/app
